site_name: DCA

nav:
  - Home: index.md
  - Install Docker: install-docker.md
  - Seccomp: seccomp.md
  - SSL Certificate: ssl-certificate.md
  - Bridge: bridge.md
  - Volumes: volume.md
  - Practice: to_read.md

theme:
  name: material